### ISSUE TITLE
Support requests==2.21.0

### ISSUE THREAD

**Issue by FYJen** [magiclabs/magic-admin-python#21]
### ✅ Prerequisites

- [*] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [*] Are you running the latest SDK version?
- [*] Are you reporting to the correct repository (`magic-admin-python`)?

### 🐛 Description

Shippo pins `requests==2.210` whereas Magic pins `requests==2.22.0`. This causes the package installation error. Magic should consider supporting earlier version(s) of requests lib.

### 🧩 Steps to Reproduce

1. Install shippo with Magic

### 🤔 Expected behavior

Installation should succeed if Magic supports requests==2.21.0

### 😮 Actual behavior

Package dependency issue.

### 💻 Code Sample

N/A

### 🌎 Environment

| Software            | Version(s) |
| ------------------- | ---------- |
| `magic-admin-python`|      0.0.4      |
| `python`            |            |
| Operating System    |            |

**Comment by FYJen** [comment]
Was able to reproduce it locally once I add the `shippo==2.0.0` to the `requirements.txt`.

```
Processing 
Collecting importlib-resources; python_version < "3.7"
  Using cached importlib_resources-3.0.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: urllib3, certifi, idna, chardet, requests, six, protobuf, varint, base58, zipp, importlib-resources, netaddr, multiaddr, ipfshttpclient, typing-extensions, hexbytes, eth-typing, parsimonious, pycryptodome, eth-hash, toolz, cytoolz, eth-utils, eth-abi, rlp, eth-keys, eth-keyfile, attrdict, eth-rlp, eth-account, websockets, pyrsistent, importlib-metadata, attrs, jsonschema, lru-dict, mypy-extensions, web3, simplejson, shippo

shippo 2.0.0 requires requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.
Successfully installed attrdict-2.0.1 attrs-19.3.0 base58-2.0.1 certifi-2020.6.20 chardet-3.0.4 cytoolz-0.10.1 eth-abi-2.1.1 eth-account-0.4.0 eth-hash-0.2.0 eth-keyfile-0.5.1 eth-keys-0.2.4 eth-rlp-0.1.2 eth-typing-2.2.1 eth-utils-1.9.3 hexbytes-0.2.1 idna-2.8 importlib-metadata-1.7.0 importlib-resources-3.0.0 ipfshttpclient-0.6.0.post1 jsonschema-3.2.0 lru-dict-1.1.6 multiaddr-0.0.9 mypy-extensions-0.4.3 netaddr-0.8.0 parsimonious-0.8.1 protobuf-3.12.4 pycryptodome-3.9.8 pyrsistent-0.16.0 requests-2.22.0 rlp-1.2.0 shippo-2.0.0 simplejson-3.16.0 six-1.15.0 toolz-0.10.0 typing-extensions-3.7.4.2 urllib3-1.25.10 varint-1.0.2 web3-5.4.0 websockets-8.1 zipp-3.1.0
```

**Comment by weiiiiiiii** [comment]
Closing as [Shippo v2.0.2 has bumped its version requirement](https://github.com/goshippo/shippo-python-client/releases/tag/v2.0.2).
