### ISSUE TITLE
Dependency unsolved requests+fastapi

### ISSUE THREAD

**Issue by PhE** [magiclabs/magic-admin-python#31]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-admin-python`)?

### 🐛 Description

Dependency conflict when installing `magic-admin` and `fastapi`  on requests and web3.

### 🧩 Steps to Reproduce

```
# pyenv local 3.6.13
# poetry add magic-admin fastapi[all]
```

### 🤔 Expected behavior

No error when installing `magic-admin` along `fastapi`

### 😮 Actual behavior

output of poetry install :
```
  SolverProblemError

  Because no versions of fastapi match >0.65.1,<0.66.0
   and fastapi (0.65.1) depends on requests (>=2.24.0,<3.0.0), fastapi (>=0.65.1,<0.66.0) requires requests (>=2.24.0,<3.0.0).
  And because magic-admin (0.0.4) depends on requests (2.22.0)
   and no versions of magic-admin match >0.0.4,<0.0.5, fastapi (>=0.65.1,<0.66.0) is incompatible with magic-admin (>=0.0.4,<0.0.5).
  So, because server depends on both magic-admin (^0.0.4) and fastapi (^0.65.1), version solving failed.
```

### 💻 Code Sample

N/A

### 🌎 Environment

| Software            | Version(s) |
| ------------------- | ---------- |
| `magic-admin-python`|  0.0.4          |
| `python`            |     3.6.13       |
| Operating System    |   ubuntu 20.04 LTS   |

**Comment by weiiiiiiii** [comment]
Closing manually as #35 has been merged. Please try the new release (v0.0.5).
