### ISSUE TITLE
DID Token Link is broken and leads to a 404 page

### ISSUE THREAD

**Issue by sydneylai** [magiclabs/magic-admin-python#44]
Quick note here, under the magic-admin-python there is a description 

"The Magic Admin Python SDK provides convenient ways for developers to interact with Magic API endpoints and an array of utilities to handle [DID Token](https://docs.magic.link/tutorials/decentralized-id)."

and the DID Token URL is broken, maybe replace with the following: 

https://magic.link/docs/auth/introduction/decentralized-id

**Comment by ayv8er** [comment]
@sydneylai Thank you!
