### ISSUE TITLE
Magic Link Doesn't validate dummy secret key 

### ISSUE THREAD

**Issue by Youssefnaguib** [magiclabs/magic-admin-python#48]
### ✅ Prerequisites

- [NO ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [YES ] Are you running the latest SDK version?
- [YES ] Are you reporting to the correct repository (`magic-admin-python`)?

### 🐛 Description

I tried to put a dummy secret key to magic link for example "123XXX456" which is obviously not a correct secret key, and code passes normally, Code should stop or raise an exception 

here is a sample screenshots

<img width="453" alt="image" src="https://user-images.githubusercontent.com/105198519/207847940-f2ad894c-425d-4bb1-b0ef-33801c9ee294.png">

code continue execution and validate token and get issuer with the dummy api secret key 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/105198519/207850534-2111039a-af9d-4a70-a01d-a799c7629673.png">

### 🧩 Steps to Reproduce

1. Initialize a class for magic link
2. add dummy secret key with try and except as per the attached image
3. you will find that code is not executing the except for ForbiddenError4. 
4. I can then validate tokens with this dummy secret key
### 🤔 Expected behavior

Code should stop or execute exception, here is a sample when trying invalid key with javascript, I need to validate the same scenario in python

<img width="443" alt="image" src="https://user-images.githubusercontent.com/105198519/207847787-3a89c85c-4bcb-4610-9bc3-43234c7393e4.png">

### 💻 Code Sample

from magic_admin import Magic
from magic_admin.error import ForbiddenError

class MagicLink:
    @classmethod
    def initialize(cls):
        try:
            magic = Magic(api_secret_key="123XXX456")
            cls.magic = magic
        except ForbiddenError as e: // should be executed
            msg = str(e)

    @classmethod
    def get_magic(cls):
        return cls.magic

### 🌎 Environment

python 3.9/3.10
MacOs 
magic-admin-python latest version

**Comment by justinnout** [comment]
Hey @Youssefnaguib thanks for reporting this? Is the ask that we support adding secret key validation upon Magic client initialization?

**Comment by Youssefnaguib** [comment]
Hello Justin

Thank you for your mail,

Yes, this is my question, When I have added dummy secret key, the code continues and didn’t catch an exception or anything,

What is the best way for handling this?

Thanks
Regards

YoussefNaguib



On 19 Dec 2022, at 7:48 PM, Justin Herrera ***@***.******@***.***>> wrote:



Hey @Youssefnaguib<https://github.com/Youssefnaguib> thanks for reporting this? Is the ask that we support adding secret key validation upon Magic client initialization?

**Comment by am-hernandez** [comment]
Hello @Youssefnaguib and thank you for reporting this. We appreciate your feedback! This is expected behavior from the SDK as no calls are made to Magic's API upon instantiation of the SDK. Without making a call to Magic's API it can't be yet known if the API key is valid.
